#!/bin/bash

#create by fuzj



Color () {
	Print_Red () { 
	echo  -e  "\033[40;31m $1  \033[0m "
	}
	Print_Green () { 
	echo -e  "\033[40;32m $1 \033[0m "
	}
	Print_Yelow () { 
	echo -n -e  "\033[40;33m $1 \033[0m "
	}
}

User_Info () {
	User="admin"
	Passwd="saadmin123"
	Host="192.168.254.5"
	Port="3306"
	Con="mysql -u $User -p$Passwd -h $Host -P $Port"

}
Config_DB () {
	User_Info
	Insert () {
	$Con -e "use sadb; insert host (Hostname,Role,Groups,IP,date,Mac) values ('$values1' , '$values2' ,'$values3', '$values4','$values5','$values6')"
	$Con -e "use sadb ; select * from host order by id desc limit 1"
	}
	
	Update () {
	$Con -e "use sadb; update host set ${values2}='${values4}' where $values1='$values3'"
	}
	Delete () {
	$Con -e "use sadb; delete host where ${values1}='${values2}'"
	}
	Select () {
	$Con  -e "use sadb; select $values2 from host where ${values1}='${values3}'"
	}


case $1 in 
Insert)
	Insert ;;
Update)
	Update ;;
Delete)
	Delete ;;
Select)
	Select ;;
*)
	echo "No rule" ;;
esac
}




Color
case $1 in
select)
	Print_Yelow "please input select Content : " 		; read -p  "" values3
	Print_Yelow "please input select Attribute : "      ; read -p  "" values1
	Print_Yelow "please input Display Option : "		; read -p  "" values2
	[ -z $values2 ] && values2="*" 
	Config_DB Select
	;;
insert)
	Print_Yelow "please input Hostname:  " ;read -p ""  values1
	Print_Yelow "please input Role: "      ;read -p ""  values2
	Print_Yelow "please input Group: "     ;read -p ""  values3
	Print_Yelow "please input IP: "        ;read -p ""  values4
	Print_Yelow "please input Mac: "       ;read -p ""  values6
	values5=`date +'%F %X'`
	Config_DB Insert 
	;;
update)
	Print_Yelow "please input will update Target :  "   	;read -p "" values1
	Print_Yelow "please input will update Target_detail: "  ;read -p "" values3
	Print_Yelow "please input will update Content:  "  		;read -p "" values4
	Print_Yelow "please input will update Attribute:  "		;read -p "" values2
	Config_DB Update
	values2="Hostname,$values2"	
	Config_DB Select
	;;
delete)
	Print_Yelow "please input will delete Content: "  ;read -p ""  values1
	Print_Yelow "please input will delete Attribute: ";read -p "" values
	Config_DB Delete
	;;
*)
	Print_Red "No Option"
	exit 1
	;;
esac
